// This file is generated by Velite

export { default as travelBlog } from './travelBlog.json'
export { default as newsBlog } from './newsBlog.json'
export { default as tipTravelBlog } from './tipTravelBlog.json'