// This file is generated by Velite

import config from '../velite.config'

type Collections = typeof config.collections

export type DiemDen = Collections['travelBlog']['schema']['_output']
export declare const travelBlog: DiemDen[]

export type TinTuc = Collections['newsBlog']['schema']['_output']
export declare const newsBlog: TinTuc[]

export type TipsDuLich = Collections['tipTravelBlog']['schema']['_output']
export declare const tipTravelBlog: TipsDuLich[]
